version: '3.9'

services:
  db:
    image: postgres:15.3
    restart: always
    environment:
      - POSTGRES_USER=${SHAREAICHAT_POSTGRES_USER}
      - POSTGRES_PASSWORD=${SHAREAICHAT_POSTGRES_PASSWORD}
      - POSTGRES_DB=${SHAREAICHAT_POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: 
      context: .
      dockerfile: docker/django/Dockerfile
    volumes:
      - static_volume:/app/staticfiles
    #ports:
    #  - "8000:8000"
    environment:
      - SECRET_KEY=${SHAREAICHAT_SECRET_KEY}
      - DEBUG=${SHAREAICHAT_DEBUG}
      - ALLOWED_HOSTS=${SHAREAICHAT_ALLOWED_HOSTS}
      - DEFAULT_FROM_EMAIL=${SHAREAICHAT_DEFAULT_FROM_EMAIL}
      - EMAIL_BACKEND=${SHAREAICHAT_EMAIL_BACKEND}
      - EMAIL_HOST=${SHAREAICHAT_EMAIL_HOST}
      - EMAIL_PORT=${SHAREAICHAT_EMAIL_PORT}
      - EMAIL_USE_TLS=${SHAREAICHAT_EMAIL_USE_TLS}
      - EMAIL_HOST_USER=${SHAREAICHAT_EMAIL_HOST_USER}
      - EMAIL_HOST_PASSWORD=${SHAREAICHAT_EMAIL_HOST_PASSWORD}
      - TURNSTILE_SECRET_KEY=${SHAREAICHAT_TURNSTILE_SECRET_KEY}
      - POSTGRES_USER=${SHAREAICHAT_POSTGRES_USER}
      - POSTGRES_PASSWORD=${SHAREAICHAT_POSTGRES_PASSWORD}
      - POSTGRES_DB=${SHAREAICHAT_POSTGRES_DB}
      - SHAREAICHAT_ENV=${SHAREAICHAT_ENV}
    depends_on:
      - db
    restart: always
  
  nginx:
    image: nginx:1.25
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./${SHAREAICHAT_NGINX_CONFIG}:/etc/nginx/conf.d/default.conf
      - static_volume:/static:ro
      - /home/sammy/certs:/etc/nginx/certs:ro
    depends_on:
      - web

volumes:
  db_data:
  static_volume: