version: '3.9'

services:
  db:
    image: postgres:15.3
    restart: always
    environment:
      - POSTGRES_USER=${SHAREAICHAT_POSTGRES_USER}
      - POSTGRES_PASSWORD=${SHAREAICHAT_POSTGRES_PASSWORD}
      - POSTGRES_DB=${SHAREAICHAT_POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data

  web:
    build: 
      context: .
      dockerfile: docker/django/Dockerfile
    volumes:
      - static_volume:/app/staticfiles
    environment:
      - SHAREAICHAT_SECRET_KEY=${SHAREAICHAT_SECRET_KEY}
      - SHAREAICHAT_DEBUG=${SHAREAICHAT_DEBUG}
      - SHAREAICHAT_ALLOWED_HOSTS=${SHAREAICHAT_ALLOWED_HOSTS}
      - SHAREAICHAT_DEFAULT_FROM_EMAIL=${SHAREAICHAT_DEFAULT_FROM_EMAIL}
      - SHAREAICHAT_EMAIL_BACKEND=${SHAREAICHAT_EMAIL_BACKEND}
      - SHAREAICHAT_EMAIL_HOST=${SHAREAICHAT_EMAIL_HOST}
      - SHAREAICHAT_EMAIL_PORT=${SHAREAICHAT_EMAIL_PORT}
      - SHAREAICHAT_EMAIL_USE_TLS=${SHAREAICHAT_EMAIL_USE_TLS}
      - SHAREAICHAT_EMAIL_HOST_USER=${SHAREAICHAT_EMAIL_HOST_USER}
      - SHAREAICHAT_EMAIL_HOST_PASSWORD=${SHAREAICHAT_EMAIL_HOST_PASSWORD}
      - SHAREAICHAT_TURNSTILE_SECRET_KEY=${SHAREAICHAT_TURNSTILE_SECRET_KEY}
      - SHAREAICHAT_POSTGRES_USER=${SHAREAICHAT_POSTGRES_USER}
      - SHAREAICHAT_POSTGRES_PASSWORD=${SHAREAICHAT_POSTGRES_PASSWORD}
      - SHAREAICHAT_POSTGRES_DB=${SHAREAICHAT_POSTGRES_DB}
      - SHAREAICHAT_ENV=${SHAREAICHAT_ENV}
    depends_on:
      - db
    restart: always
  
  caddy:
    image: caddy:2
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - static_volume:/static
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - web

volumes:
  db_data:
  static_volume:
  caddy_data:
  caddy_config: