# Generated by Django 4.2.2 on 2023-09-27 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_votetimestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='extra_info',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
